CREATE TABLE IF NOT EXISTS test_data (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL, 
  email VARCHAR(100) NOT NULL UNIQUE,
  title VARCHAR(100) NOT NULL, 
  date_js VARCHAR(170) NOT NULL, 
  description VARCHAR(1000) NULL NULL, 
  assessment INT NOT NULL,
  date_test_php TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);