CREATE TABLE IF NOT EXISTS test_events (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL, 
  mini_desk VARCHAR(255) NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  regional VARCHAR(100) NOT NULL, 
  full_desk TEXT NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);